config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :message_threads
  resources :message_thread_users
  resources :goals
  resources :requests

  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :participations
  resources :users, only: [:show]

  get 'pages/welcome'
  get 'pages/about'
  get 'pages/contact'

  root "pages#welcome"

end

app/models/goal.rb
class Goal < ActiveRecord::Base
  belongs_to :leader, class_name: "User"
  has_many :participations
  has_many :users, through: :participations
  has_many :requests


  def save_create_participation(goal, user_id)
    goal.save
    Participation.create(goal_id: goal.id, status: "Creator", user_id: user_id)
  end

  GOAL_CATEGORIES = [
    "Business/Career",
    "Education",
    "Health/Fitness",
    "Finance",
    "Personal Development",
    "Recreation",
    "Relationship",
    "Social",
    "Spiritual"
  ]


end#Goal

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: [:edit, :update, :destroy]
  before_action :set_goal_includes, only: [:show]


  # GET /goals
  # GET /goals.json
  def index
    @goals = Goal.all
  end

  # GET /goals/1
  def show
    #if currrent user !particpant && goal open for new participants
    @request = Request.new
    #end
    @participations = @goal.participations
    @requests = @goal.requests

    @goal_requested = current_user.goal_requested?(@goal.id) if user_signed_in?

  end

  # GET /goals/new
  def new
    @goal = Goal.new
  end

  # GET /goals/1/edit
  def edit
  end

  # POST /goals
  def create
    @goal = Goal.new(goal_params)
    if @goal.save_create_participation(@goal, current_user.id)
      redirect_to @goal, notice: 'Goal was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /goals/1
  def update
    respond_to do |format|
      if @goal.update(goal_params)
        format.html { redirect_to @goal, notice: 'Goal was successfully updated.' }
        format.json { render :show, status: :ok, location: @goal }
      else
        format.html { render :edit }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goals/1
  def destroy
    @goal.destroy
    respond_to do |format|
      format.html { redirect_to goals_url, notice: 'Goal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goal_includes
      @goal = Goal.includes(:participations, :requests).where(id: params[:id]).first
    end

    def set_goal
      @goal = Goal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def goal_params
      params.require(:goal).permit(:title, :description, :status, :category)
    end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/_form.html.erb
<%= form_for(@goal) do |f| %>
  <% if @goal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@goal.errors.count, "error") %> prohibited this goal from being saved:</h2>

      <ul>
      <% @goal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/goals/_goal.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= goal.title %>
      <h5><%= link_to 'View', goal %></h5>
    </h3>
  </div>
  <div class="panel-body">
    <%= goal.description %>
  </div>
</div>

app/views/goals/edit.html.erb
<h1>Editing Goal</h1>

<%= render 'form' %>

<%= link_to 'Show', @goal %> |
<%= link_to 'Back', goals_path %>

app/views/goals/index.html.erb
<% @goals.each do |goal| %>
  <%= render partial: "goal", locals: {goal: goal} %>
<% end %>

<%= link_to 'New Goal', new_goal_path %>

app/views/goals/new.html.erb
<h1>New Goal</h1>

<%= render 'form' %>

<%= link_to 'Back', goals_path %>

app/views/goals/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @goal.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @goal.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @goal.status %>
</p>

<p>
  <strong>Category:</strong>
  <%= @goal.category %>
</p>

<h1>Participants</h1>
<% @participations.each do |participation| %>
  <div>
    <%= participation.user.username %> |
    <%= participation.status %>
  </div>
<% end %>

<% if current_user == @goal.leader %>
  <h1>Pending Requests</h1>
  <% @requests.pending.each do |request| %>
    <div>
      <%= link_to request.user.username, user_path(request.user)   %> |
      <%= link_to request.status, edit_request_path(request) %>
    </div>
  <% end %>
<% else %>
  <% if @goal_requested %>
    <p> Your request is pending </p>
  <% else %>
    <%= form_for(@request) do |f| %>
      <%= hidden_field_tag("request[goal_id]", @goal.id) %>
      <%= f.submit "Request to Join" %>
    <% end %>
  <% end %>
<% end %>


<%= link_to 'Edit', edit_goal_path(@goal) %> |
<%= link_to 'Back', goals_path %>