config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :message_threads
  resources :message_thread_users
  resources :goals
  resources :requests

  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :participations
  resources :users, only: [:show]

  get 'pages/welcome'
  get 'pages/about'
  get 'pages/contact'

  root "pages#welcome"

end

app/models/goal.rb
class Goal < ActiveRecord::Base
  belongs_to :leader, class_name: "User"
  has_many :participations
  has_many :users, through: :participations
  has_many :requests


  def save_create_participation(goal, user_id)
    goal.save
    Participation.create(goal_id: goal.id, status: "Creator", user_id: user_id)
  end

  GOAL_CATEGORIES = [
    "Business/Career",
    "Education",
    "Health/Fitness",
    "Finance",
    "Personal Development",
    "Recreation",
    "Relationship",
    "Social",
    "Spiritual"
  ]


end#Goal

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :message_thread
  belongs_to :user
end

app/models/message_thread.rb
class MessageThread < ActiveRecord::Base
  has_many :message_thread_users
  has_many :users, through: :message_thread_users
  has_many :messages


end

app/models/message_thread_user.rb
class MessageThreadUser < ActiveRecord::Base
  belongs_to :message_thread
  belongs_to :user
end

app/models/participation.rb
class Participation < ActiveRecord::Base
  belongs_to :goal
  belongs_to :user
end

app/models/private_message_state.rb
class PrivateMessageState < ActiveRecord::Base
  belongs_to :private_messag
  belongs_to :user
end

app/models/request.rb
class Request < ActiveRecord::Base
  VALID_STATUS = ['Accepted', 'Pending', 'Declined']
  belongs_to :user
  belongs_to :goal

  before_create :set_status
  validate :status_values, on: :update
  scope :pending, -> { where(status: 'Pending') }


  private
    def set_status
      self.status = "Pending"
    end

    def status_values
      errors.add(:status, 'is not valid status') unless VALID_STATUS.include?(self.status)
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :leaderships, class_name: "Goal", foreign_key: :leader_id
  has_many :participations
  has_many :goals, through: :participations
  has_many :requests

  has_many :messages
  has_many :message_thread_users
  has_many :message_threads, through: :message_thread_users
  has_many :received_messages, through: :message_threads, source: :message



  # ActiveRecord::HasManyThroughSourceAssociationNotFoundError: Could not find the source association(s) "received_message" or :received_messages in model MessageThread. Try 'has_many :received_messages, :through => :message_threads, :source => <name>'. Is it one of message_thread_users?

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, uniqueness: true

  def goal_requested?(goal_id)
    requests.map(&:goal_id).include?(goal_id)
  end

  def create_new_message_and_thread(receiver_id)
    message_thread = MessageThread.create
    message_thread.message_thread_users.create(user_id: receiver_id)
    self.message_thread_users.create(message_thread_id: message_thread.id)
    self.messages.new(message_thread_id: message_thread.id)
  end



end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: [:edit, :update, :destroy]
  before_action :set_goal_includes, only: [:show]


  # GET /goals
  # GET /goals.json
  def index
    @goals = Goal.all
  end

  # GET /goals/1
  def show
    #if currrent user !particpant && goal open for new participants
    @request = Request.new
    #end
    @participations = @goal.participations
    @requests = @goal.requests

    @goal_requested = current_user.goal_requested?(@goal.id) if user_signed_in?

  end

  # GET /goals/new
  def new
    @goal = Goal.new
  end

  # GET /goals/1/edit
  def edit
  end

  # POST /goals
  def create
    @goal = Goal.new(goal_params)
    if @goal.save_create_participation(@goal, current_user.id)
      redirect_to @goal, notice: 'Goal was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /goals/1
  def update
    respond_to do |format|
      if @goal.update(goal_params)
        format.html { redirect_to @goal, notice: 'Goal was successfully updated.' }
        format.json { render :show, status: :ok, location: @goal }
      else
        format.html { render :edit }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goals/1
  def destroy
    @goal.destroy
    respond_to do |format|
      format.html { redirect_to goals_url, notice: 'Goal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goal_includes
      @goal = Goal.includes(:participations, :requests).where(id: params[:id]).first
    end

    def set_goal
      @goal = Goal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def goal_params
      params.require(:goal).permit(:title, :description, :status, :category)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = current_user.create_new_message_and_thread(params[:receiver_id])

  end

  # GET /messages/1/edit
  def edit
  end


  def create
    @message = Message.new(message_params)
      if @message.save
        redirect_to @message, notice: 'Message was successfully created.'
      else
        render :new
      end
  end

  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:message_thread_id, :user_id, :content)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:home, :show]

  def show
    if @user == current_user
      @threads = current_user.message_threads(include: :messages)
      render "home"
    else
      @message = current_user.messages.new
    end
  end

private

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/message_threads_helper.rb
module MessageThreadsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/participations_helper.rb
module ParticipationsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Abildy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav>

  </nav>

  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Abildy", root_path, class: "navbar-brand" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Goals", goals_path %></li>
          <% if current_user %>
            <li><%= link_to "My Goals", participations_path %></li>
            <li><%= link_to "Signed in as #{current_user.username}", user_path(current_user) %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign In", new_user_session_path %></li>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <div class="container-fluid">
    <!-- <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p> -->
    <%= yield %>
  </div>

</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/welcome.html.erb
<div class="jumbotron">
  <h1>Welcome to Abildy</h1>
  <p>Acheive your goals with an Accountability Buddy</p>
  <%= link_to "Learn More", pages_about_path, class: "btn btn-primary btn-lg" %>
</div>